-- phpMyAdmin SQL Dump
-- version 4.8.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 10-05-2019 a las 21:58:08
-- Versión del servidor: 10.1.32-MariaDB
-- Versión de PHP: 5.6.36

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `peliculasseries`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `peliculas`
--

CREATE TABLE `peliculas` (
  `idpelicula` int(100) NOT NULL,
  `titulo` varchar(100) NOT NULL,
  `year` varchar(100) NOT NULL,
  `genero` varchar(100) NOT NULL,
  `actores` varchar(100) NOT NULL,
  `descripcion` longtext NOT NULL,
  `imagen` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `peliculas`
--

INSERT INTO `peliculas` (`idpelicula`, `titulo`, `year`, `genero`, `actores`, `descripcion`, `imagen`) VALUES
(1, 'Spider-Man Lejos de casa', '5 de julio de 2019 ', 'Accion  Fantasia', 'Tom Holland, Zendaya, Marisa Tomei', 'Peter Parker (Tom Holland) decide dejar sus heroicidades a un lado durante unas pocas semanas, y sale de viaje por Europa con sus amigos Ned (Jacob Batalon), MJ (Zendaya) y el resto de companeros de instituto. Pero las vacaciones de verano daran un giro inesperado cuando aparezca Nick Furia (Samuel L. Jackson), que tiene trabajo para Peter. Varias criaturas elementales, seres hechos de arena, piedra, agua y fuego, estan creando el caos y la destruccion en todo el continente. El joven Hombre Arana debera desentranar el misterio de estos ataques. Solo y con sus amigos en apuros, ademas de con la nueva aparicion de Mysterio (Jake Gyllenhaal), Peter tendra que decidirse a dar la cara. Esta secuela de Spider-Man: Homecoming (2017), basada en los comics de Marvel creados por Steve Ditko y Stan Lee, esta dirigida por Jon Watts (Coche policial) y vuelve a contar con guion de Chris McKenna y Erik Sommers. Protagonizan la pelicula Tom Holland (Vengadores: Endgame), Zendaya (El gran showman), Jacob Batalon (Vengadores: Infinity War), Samuel L. Jackson (Glass (Cristal)), Jake Gyllenhaal (Velvet Buzzsaw), Cobie Smulders (Una serie de catastroficas desdichas), Jon Favreau (El libro de la selva), Michael Keaton (Dumbo), Laura Harrier (Infiltrado en el KKKlan), Remy Hii (Harrow), Numan Acar (Aladdin) y Marisa Tomei (Y de repente tu).', 'Spider.jpg'),
(2, 'Tolkien', '14 de junio de 2019', 'Biografia, Drama', 'Nicholas Hoult, Lily Collins, Craig Roberts', 'Todo el mundo a oido hablar de J.R.R. Tolkien, el escritor de la famosa trilogia de \"El senor de los anillos\", asi como del conocido libro \"El hobbit\". El escritor es conocido mundialmente y sus obras ya han sido adaptadas como peliculas, consiguiendo beneficios millonarios en taquilla. Ahora, ademas, su propia figura sera la que realizara el salto a la gran pantalla. La pelicula tratara sobre su vida y su obra, centrandose sobre todo en como los acontecimeintos que ocurrieron en la primera afectaron a la segunda. Hollywood ya ha empezado a trabar en el biopic, y el conocido guionista David Gleeson ya ha comenzado a escribir el guion. El productor del filme es Peter Chernin, y se estan barajando nombres tanto para dirigir Tolkien como para actuar en ella. Tampoco se conoce la fecha en la que el proyecto se convertira finalmente en realidad, pero se comenta que puede que para 2015 la pelicula este lista para su estreno.', 'tolkien.jpg'),
(3, 'El hijo', '24 de mayo de 2019', ' Terror', 'Elizabeth Banks, David Denman, Matt L. Jones', 'Todo lo que el matrimonio protagonista ha querido siempre es algo teoricamente simple: un hijo. A pesar de los intentos, ese deseo no parece hacerse realidad. Hasta que, una noche, un meteorito cae en la granja en la que estos viven. El mismo resulta ser una nave que contiene a un nino dentro. Conforme este va creciendo, descubre que tiene unas habilidades especiales que no le permiten encajar con el resto, unas habilidades que, de forma contraria a lo que se podria pensar, acaban sacando lo peor de si mismo.', 'hijo.jpg'),
(4, 'John Wick:Capitulo 3', '31 de mayo de 2019', ' Accion', ' Keanu Reeves, Asia Kate Dillon, Ian McShane', 'En el segundo capitulo de John Wick 2 -Pacto de Sangre- vimos como nuestro heroe es obligado a volver a su vida de sicario. El gangster Santino D\'Antonio ayudo a John en el pasado y ahora le toca a Wick devolverle el favor. Santino encarga al sicario asesinar a su hermana, la que se encuentra a la cabeza de una de las mafias. El protagonista cumple con la tarea que se le ha encomendado, pero esto despierta un inesperado odio en Santino, que no acepta la muerte de su hermana a pesar de que la deseaba con todas sus fuerzas. De este modo, John Wick comienza a ser perseguido por todas las mafias que simpatizan con el italiano.', 'wick.png'),
(5, 'Sonic La pelicula', '27 de diciembre de 2019', ' Aventura', ' James Marsden, Jim Carrey, Tika Sumpter', 'Sonic, el famoso erizo azul de SEGA vivira su primera aventura en la pantalla grande. En esta adaptacion cinematografica basada en la conocida saga de videojuegos podremos ver a los personajes iconicos de la franquicia. Su protagonista sera Sonic, el erizo con la habilidad de correr a la velocidad del sonido y que, junto con sus amigos el zorro Tails y el equidna Knuckles, combaten con el malvado Doctor Eggman, que siempre esta tratando de dominar el mundo y apoderarse de las esmeraldas del caos.Esta pelicula, que incluira tanto accion real como animacion creada por ordenador, esta escrita por Patrick Casey y Josh Miller, responsables de la mini-serie 12 Deadly Days (2016) y de la serie de animacion Golan the Insatiable. Debuta como director en esta adaptacion del videojuego Jeff Fowler, responsable del corto de animacion Gopher Broke (2004). Por su parte, Tim Miller, director de Deadpool (2016), es productor ejecutivo del filme.', 'sonic.jpg'),
(6, 'Aladdin', '24 de mayo de 2019', ' Aventura, Familia, Fantasia', 'Mena Massoud, Naomi Scott, Will Smith', 'Rodeada por los Siete Desiertos, se encuentra la ciudad de Agrabah, una metropoli de calles estrechas y plagadas de gente, donde en lo mas alto puede verse el majestuoso castillo del Sultan. Alli vive la joven princesa Jasmine (Naomi Scott) junto con su padre el Sultan (Navid Negahban) y el visir real Jafar (Marwan Kenzari). La vida de todos ellos dara un giro inesperado despues de que el joven Aladdin (Mena Massoud) entre en la Cueva de las Maravillas y descubra la lampara magica cuyo Genio (Will Smith) tiene el poder omnipotente de conceder tres deseos a cualquiera que la posea.Esta nueva adaptacion musical en accion real del clasico de Disney Aladdin (1992) esta dirigida por Guy Ritchie (Rey Arturo: La leyenda de Excalibur, Sherlock Holmes: Juego de sombras), y el guion lo firma John August (Frankenweenie, Charlie y la fabrica de chocolate). El reparto protagonista del filme esta formado por Mena Massoud (Jack Ryan) como Aladdin, Naomi Scott (Power Rangers) como Jasmine, Marwan Kenzari (Asesinato en el Orient Express) como el villano Jafar, Nasim Pedrad (New Girl) como Dalia, Navid Negahban (12 valientes) como el sultan de Agrabah, Billy Magnussen (Maniac) como el Principe Anders y Will Smith (Bright) como el Genio.', 'aladdin.jpg'),
(7, 'It: Capitulo 2', '6 de septiembre de 2019', 'Terror', ' Bill Skarsgård, James McAvoy, Jessica Chastain', 'En esta segunda parte de It sabremos el desenlace de la peligrosa mision de \"El club de los perdedores\", la pandilla de amigos de la infancia que han decidido acabar con Pennywise, el monstruoso y sadico payaso que ha sembrado el caos en Derry, su pueblo natal. Andres Muschietti (Mama) dirige de nuevo esta adaptacion a la gran pantalla de la famosa novela homonima de Stephen King, que cuenta con un guion escrito por por Gary Doberman (Annabelle). El actor Bill Skarsgård (La serie Divergente: Leal - 1ª parte, Hemlock Grove) repite en la piel del terrible Pennywise.', 'it2.jpg'),
(8, 'Hellboy', '17 de mayo de 2019', 'Fantasia, Accion', ' David Harbour, Milla Jovovich, Ian McShane', 'Vuelve Hellboy (David Harbour), el gran demonio de piel roja, con cola, cuernos y un brazo de piedra. Atrapado entre los mundos de lo sobrenatural y lo humano, el apodado como \'El mas grande Investigador de lo Paranormal del Mundo\' junto con la Agencia para la Investigacion y Defensa Paranormal (A.I.D.P.) tendran un nuevo y peligroso desafio. Su mision sera enfrentarse a una nueva y poderosa amenaza: Nimue (Milla Jovovich), conocida como La Reina de la Sangre, un espiritu ancestral de la epoca del rey Arturo que ha vuelto a nuestro mundo llena de sed de venganza para sembrar el terror y destruir a la raza humana.Basado en las novelas graficas de Mike Mignola, el demonio Hellboy vuelve en este reboot de las cintas originales de Guillermo del Toro, que dirige Neil Marshall (Centurion). El propio Mignola ha co-escrito el guion de la pelicula junto a Christopher Golden (Ghosts of Albion: Embers) y Andrew Cosby (Eureka). Sus protagonistas son David Harbour (Stranger Things) que interpreta al demonio de piel roja y Milla Jovovich (Resident Evil: El capitulo final) que encarna a La Reina de la Sangre. Completan el reparto Ian McShane (John Wick: Pacto de sangre), Daniel Dae Kim (La serie divergente: Leal), Sasha Lane (American Honey), Penelope Mitchell (Cronicas vampiricas), Sophie Okonedo (After Earth) y Brian Gleeson (El hilo invisible).', 'Hellboy.jpg'),
(9, 'Stuber', '24 de mayo de 2019', ' Comedia, Accion', ' Dave Bautista, Kumail Nanjiani, Betty Gilpin', 'Stuber es una comedia que parodia el servicio Uber. Stu es un educado conductor de Uber que recoge a un policia que esta persiguiendo a un asesino. Kumail Nanjiani (Silicon Valley, La gran enfermedad del amor) interpreta a Stu, el conductor, mientras que Dave Bautista (Guardianes de la Galaxia) interpreta al policia. Tambien forman parte del reparto, Betty Gilpin (Glow), Mira Sorvino (Poderosa Afrodita) e Iko Uwais (Redada asesina). Michael Dowse (Amigos de mas) dirige esta comedia policiaca.', 'Stuber.jpg'),
(10, 'Venganza bajo cero', '28 de junio de 2019', ' Accion, Drama', 'Liam Neeson, Tom Bateman, Tom Jackson', 'En plenas montanas, viviendo entre la nieve, un apacible quitanieves vive tranquilamente en la naturaleza. Pero un dia toda su paz se desmorona, pues recibe la terrible noticia de que su hijo ha muerto debido a una sobredosis. De esta forma acaba envuelto en una guerra de narcotraficantes, mientras busca venganza por lo sucedido. Hans Petter Moland (Redencion: Los casos del departamento Q) dirige el remake de su propia pelicula del 2014, que en esta ocasion cuenta con un guion escrito por Frank Baldwin (The Godmother) y con Liam Neeson (Un monstruo viene a verme) como protagonista.', 'venganza.jpg'),
(11, 'X-Men: Fenix Oscura', '7 de junio de 2019', ' Aventura Accion Ciencia ficcion', ' Sophie Turner, James McAvoy, Michael Fassbender', 'Esta vez los X-MEN se enfrentan a su enemigo mas poderoso: uno de sus propios miembros, Jean Grey (Sophie Turner). Durante una mision de rescate en el espacio, Jean casi muere al ser alcanzada por una misteriosa fuerza cosmica. Cuando regresa a casa, esta fuerza no solo la ha hecho infinitamente mas poderosa, tambien ahora es mas inestable. Mientras lucha con la entidad que habita en su interior, Jean desata sus poderes de formas que no puede controlar ni comprender. Jean caera en una espiral fuera de control haciendo dano a aquellos que mas ama, comenzando a destruir los lazos que mantienen unidos a los X-Men. Mientras su familia se desmorona, deberan encontrar la forma de unirse, no solo para salvar el alma de Jean, sino tambien para salvar el planeta de unos alienigenas que quieren transformar esta fuerza en un arma y conquistar la galaxia.Simon Kingber, guionista de X-Men: Apocalipsis (2016) y X-Men: Dias del futuro pasado (2014), se encarga de dirigir este filme que supone un nuevo paso dentro de la franquicia mutante. Protagonizada por Sophie Turner (Juego de Tronos) como Jean Grey/Fenix Oscura, el resto del reparto lo completan Nicholas Hoult (Rebelde entre el centeno), Tye Sheridan (Ready Player One), Kodi Smit-McPhee (El amanecer del planeta de los simios), James McAvoy (Multiple), Jennifer Lawrence (Gorrion rojo), Michael Fassbender (El muneco de nieve) y Jessica Chastain (Molly\'s Game), entre otros.', 'xmen.jpg'),
(12, 'El Rey Leon', '19 de julio de 2019 ', 'Aventura Familia', ' Donald Glover, Beyonce Knowles-Carter, Chiwetel Ejiofor', 'Simba es un pequeno leon, principe de la sabana africana, que vive feliz junto a su familia. Pero su apacible vida se vera truncada cuando su ambicioso tio Scar cumpla su plan y asesine a Mufasa, el padre de Simba, para ocupar su lugar en el trono. Sera entonces cuando el pequeno leon decida escapar para salvar su vida y comenzar una nueva aventura adentrandose en solitario en la selva, donde conocera nuevos amigos que le ayudaran a convertirse en un adulto. Este remake de la pelicula de animacion El rey leon (1994) es una nueva adaptacion cinematografica en imagen real que dirige Jon Favreau (El libro de la selva, Iron Man) y que cuenta con guion de Jeff Nathanson (Piratas del Caribe: La venganza de Salazar). En el reparto de voces protagonistas de la version original estan los actores Donald Glover (Spider-Man: Homecoming) como Simba, James Earl Jones (Rogue One: Una historia de Star Wars) como Mufasa, Seth Rogen (Malditos vecinos 2) en el papel de Pumba, Billy Eichner (American Horror Story) como Timon, Chiwetel Ejiofor (Maria Magdalena) en el papel de Scar, John Oliver (Decline of the American Empire) como Zazu, Alfre Woodard (Luke Cage) como Sarabi, Florence Kasumba (Black Panther) como Shenzi, Keegan-Michael Key (¿Tenia que ser el?) como Kamari, John Kani (Capitan America: Civil War) como el sabio Rafiki, ademas de la cantante Beyonce como Nala.', 'lion.jpg'),
(13, 'Godzilla', '21 de junio de 2019', 'Accion, Ciencia ficcion', ' Vera Farmiga, Kyle Chandler, Millie Bobby Brown', 'Vuelve Godzilla, el reptil gigante japones mas famoso de la historia del cine. Esta secuela de la pelicula Godzilla (2014) esta dirigida por Michael Dougherty (Krampus: Maldita Navidad, Truco o trato), que ha co-escrito el guion del filme junto a Zach Shields (Krampus: Maldita Navidad) y Max Borenstein (Kong: La Isla Calavera). El reparto protagonista esta formado por los actores Vera Farmiga (Expediente Warren: El caso Enfield, Codigo fuente), Kyle Chandler (Manchester frente al mar, El lobo de Wall Street), O\'Shea Jackson Jr. (Ingrid Goes West, Straight Outta Compton), Aisha Hinds (La cupula, Star Trek: En la oscuridad) y Millie Bobby Brown (Stranger Things, Intruders).', 'godzilla.jpg'),
(14, 'Toy Story 4', '21 de junio de 2019', ' Familia Animacion Aventura', ' Tom Hanks, Tim Allen, Tony Hale', 'El sheriff Woody y el miembro del Comando Estelar Buzz Lightyear, junto al resto de sus inseparables companeros de cuarto, vuelven a la carga. Ahora viven en una habitacion nueva, con juguetes nuevos como Ducky y Bunny. Pero cuando un juguete llamado Forky se una a Woody y su pandilla, comenzara una trepidante aventura junto a viejos y nuevos amigos que les revelara lo grande que puede ser el mundo para un juguete.Cuarta entrega de la saga Toy Story que en esta ocasion dirige Josh Cooley, que debuta en la direccion de largometrajes con este filme tras encargarse del guion Del reves (Inside Out) (2015). El reparto de voces del filme en version original contara de nuevo con Tom Hanks (Los archivos del Pentagono) como Woody, Tim Allen (Uno para todas) como Buzz Lightyear, Annie Potts (El joven Sheldon) como Bo Peep y Joan Cusack (Las ventajas de ser un marginado) como Jessie. Se incorporan al reparto de voces Tony Hale (Con amor, Simon), Patricia Arquette (Boardwalk Empire), Keegan-Michael Key (Predator) y Jordan Peele (La vida en piezas)', 'toy.jpg'),
(15, 'Dumbo', ' 29 de marzo de 2019', 'Familia, Aventura', ' Colin Farrell, Danny DeVito, Michael Keaton ', 'Dumbo es un pequeno elefante nacido en el circo de Max Medici (Danny DeVito). Sus enormes orejas le convierten rapidamente en el hazmerreir de todos, excepto de dos jovenes ninos, Joe (Finley Hobbins) y Milly (Nico Parker), los hijos de Holt Farrier (Colin Farrell), una ex estrella de circo que acaba de regresar de la guerra y que debe hacer frente a los cambios de su vida mientras se ocupa de este pequeno animal. Pero la vida de este tierno paquidermo cambiara cuando descubra que precisamente gracias a sus grandes orejas puede volar. En ese momento, el emprendedor V.A Vandevere (Michael Keaton) y la acrobata aerea Colette Marchant (Eva Green) intentaran convertirlo en toda una estrella. ', 'dumbo.jpg'),
(16, 'VENGADORES: ENDGAME', ' 25 de abril de 2019', ' Accion, Fantasia, Aventura', ' Robert Downey Jr., Chris Evans, Mark Ruffalo', 'Despues de los devastadores eventos ocurridos en Vengadores: Infinity War, el universo esta en ruinas debido a las acciones de Thanos, el Titan Loco. Tras la derrota, las cosas no pintan bien para los Vengadores. Mientras Iron Man (Robert Downey Jr.) vaga en soledad junto a Nebula (Karen Gillan) en una nave lejos de la Tierra, el grupo encabezado por Capitan America (Chris Evans), Viuda Negra (Scarlett Johansson), Hulk (Mark Ruffalo) y Thor (Chris Hemsworth) debera tratar de revertir los efectos de la catastrofe provocada por Thanos. Los Vengadores deberan reunirse una vez mas para deshacer sus acciones y restaurar el orden en el universo de una vez por todas. Esta vez, contaran tambien con aliados como Ojo de Halcon (Jeremy Renner) y Capitana Marvel (Brie Larson), ademas de Ant-Man (Paul Rudd), que presumiblemente podria haber estado atrapado en el Reino Cuantico. Juntos, se prepararan para la batalla final, sin importar cuales sean las consecuencias.', 'endgame.jpg'),
(17, ' Shazam', '5 de abril de 2019', 'Accion, Fantasia', ' Zachary Levi, Asher Angel, Mark Strong', 'Todos llevamos un superheroe en nuestro interior. Solo es preciso un poco de magia para sacarlo. Es lo que le ocurre a Billy Batson (Asher Angel), un joven huerfano de 14 anos, normal y corriente, al que le cambia la vida un encuentro con un viejo hechicero. Y es que, a partir de ahora, cada vez que Billy grita la palabra \'Shazam!\' se convierte en el superheroe adulto Shazam (Zachary Levi). Aunque con un nino en su interior, el poderoso cuerpo de Shazam hace lo que cualquier adolescente con superpoderes haria: ¡pasarselo bien! ¿Puede volar? ¿Tiene vision de rayos X? ¿Puede lanzar rayos de sus manos? ¿Puede saltarse los examenes? Shazam pondra al limite sus habilidades con la imprudencia de un nino. Claro que Billy va a necesitar controlar rapidamente estos poderes para poder defenderse de las fuerzas del mal controladas por el Doctor Thaddeus Sivana (Mark Strong)', 'shazam.jpg'),
(18, 'Pokemon Detective', ' 10 de mayo de 2019 ', ' Aventura, Accion', ' Justice Smith, Kathryn Newton', 'Ryme City, una metropoli futurista en la que los humanos y los Pokemon conviven en armonia. Tras la misteriosa desaparicion de su padre, toda una leyenda en la ciudad, el joven Tim Goodman (Justice Smith) comienza una investigacion para buscarle y averiguar lo que le ha sucedido. En esta mision le ayudara el adorable super-detective Pikachu, un inteligente Pokemon que habla, aunque curiosamente el chico es el unico que puede entenderle. Ambos uniran sus fuerzas y trabajaran juntos para resolver este gran misterio, con la ayuda de Lucy (Kathryn Newton), una reportera que trabaja en su primera gran historia. Sera una aventura en la que descubriran a entranables personajes del universo Pokemon, ademas de una trama espeluznante que podria amenazar la convivencia pacifica de todo este universo.', 'pokemon.jpg'),
(19, 'mula', '8 de marzo de 2019 ', 'Drama', 'Clint Eastwood, Bradley Cooper,', 'Earl Stone (Clint Eastwood) es un anciano horticultor de cerca de 90 anos, veterano de la Segunda Guerra Mundial. Earl esta solo y en quiebra, ya que se enfrenta a una ejecucion hipotecaria de su negocio. Es entonces cuando le ofrecen un trabajo que simplemente le exige conducir. Todo parece bastante facil, pero, sin Earl saberlo, lo que realmente esta haciendo es transportar cocaina para un cartel mexicano. Todo se complica cuando el agente de la DEA, Colin Bates (Bradley Cooper) empiece a investigar esta misteriosa mula que transporta drogas para el cartel mexicano de Sinaloa.', 'mula.jpg'),
(20, 'Bohemian Rhapsody', '31 de octubre de 2018', 'Biografia', ' Rami Malek Gwilym Lee Lucy Boynton', 'Son los anos 70. El cantante Freddie Mercury, el guitarrista Brian May, el baterista Roger Taylor y el bajista John Deacon forman la banda britanica de rock Queen. Seria en 1975 cuando su sencillo Bohemian Rhapsody les colocaria en un primer plano de la escena musical internacional. El filme es una cronica del meteorico ascenso al Olimpo de la musica de esta banda, a traves de sus iconicas canciones y su revolucionario sonido, desde que Mercury se uniera a Brian May y Roger Taylor, hasta el macroconcierto Live Aid de 1985 en el estadio de Wembley, seis anos antes de que Mercury muriera de forma prematura. Una celebracion rotunda y sonora de Queen y de su extraordinario e inclasificable cantante. Este biopic del celebre Freddie Mercury, cantante, compositor y fundador de la banda de rock Queen, esta dirigido por Dexter Fletcher (Eddie el Aguila, Amanece en Edimburgo). El actor Rami Malek (Mr. Robot, Noche en el museo: El secreto del faraon) interpreta al lider y vocalista de la banda, mientras que Ben Hardy (X-Men: Apocalipsis) da vida a Roger Taylor, baterista del grupo Queen, Joseph Mazzello (La red social) al bajista John Deacon y Gwilym Lee (Jamestown) a Brian May, guitarrista principal. Completan el reparto Aidan Gillen (Rey Arturo: La leyenda de Excalibur) como John Reid, el representante de Queen entre 1975 y 1978, y Tom Hollander (Mision: Imposible - Nacion secreta) como Jim Beach, el sustituto de Reid como manager del grupo. El filme tambien cuenta con los actores Mike Myers (Malditos bastardos), Aaron McCusker (The Astronaut Wives Club) y Lucy Boynton (Asesinato en el Orient Express).', 'bohemian.jpg'),
(21, 'Green Book', '1 de febrero de 2019 ', 'Drama', 'Viggo Mortensen, Mahershala Ali', 'Estados Unidos, anos 60. Tony Lip (Viggo Mortensen) es un brusco y malhablado italoamericano que consigue trabajo como conductor del Dr. Don Shirley (Mahershala Ali), un refinado y conocido pianista afroamericano. Juntos, realizaran una gira de conciertos desde Manhattan hasta los conservadores estados del Sur. Lip acompanara y protegera al pianista durante este tour musical, en el que se guiaran por \'El Libro Verde\', una guia con los alojamientos de los estados surenos donde los ciudadanos negros podian pasar la noche. Con el racismo y el peligro de fondo, esta inusual pareja se vera obligada a dejar de lado sus diferencias para salir adelante en el que sera el viaje de su vida.Inspirada en en la vida real de Tony Lip, esta comedia dramatica esta dirigida por Peter Farrelly (Dos tontos todavia mas tontos, Matrimonio compulsivo), que ha escrito el guion junto a Nick Vallelonga (The Corporate Ladder) y Brian Hayes Currie (Two Tickets to Paradise). El filme esta protagonizado por Viggo Mortensen (Captain Fantastic) y Mahershala Ali (Moonlight). Completan el reparto P.J. Byrne (Proyecto Rampage), Don Stark (Cafe Society) y Linda Cardellini (Dos padres por desigual).', 'gree.jpg'),
(22, 'El bueno, el feo y el malo', '7 de agosto de 1968', 'Western', ' Clint Eastwood, Eli Wallach, Lee Van Cleef', 'Durante la Guerra de Secesion, tres hombres se lanzan en busca de un arca que contiene 200.000 dolares en monedas de oro robadas al ejercito sudista. Tuco sabe que el tesoro se encuentra en un cementerio, mientras que Joe conoce el nombre inscrito sobre la lapida sepulcral que sirve de escondite. Se necesitan el uno al otro. Pero aparece un tercer hombre: Setenza, un desalmado que no vacila en masacrar a mujeres y ninos para conseguir lo que quiere.Escrita y dirigida por Sergio Leone (\'La muerte tenia un precio\', \'Por un punado de dolares\'), \'El bueno, el feo y el malo\' es una de las peliculas de western mas conocidas de toda la historia del cine. Clint Eastwood (\'Gran Torino\', \'Million Dolar Baby\') es el gran protagonista del largometraje y el que le dio una gran popularidad como actor en su papel del \"Bueno\". Eli Wallach (\'El Padrino. Parte III\', \'Los siete magnificos\') encarna a Tuco como el “Feo” y Lee Van Cleef (La muerte tenia un precio, Solo ante el peligro) se mete en la piel de Angel Eyes como el \"Malo\". Todo un clasico.', 'feo.jpg'),
(23, 'After', '12 de abril de 2019', 'Romantico', 'Josephine Langford, Hero Fiennes', 'Tessa Young (Josephine Langford) es una dedicada estudiante, una hija responsable y una novia fiel. La joven tiene grandes aspiraciones de cara a su futuro en su primer ano de universidad. Su mundo cambiara cuando, en su viaje de autodescubrimiento y de despertar sexual, conozca al oscuro, rebelde y misterioso Hardin Scott (Hero Fiennes Tiffin). Adaptacion cinematografica de la exitosa saga de novelas escritas por Anna Todd, que dirige la realizadora estadounidense Jenny Gage (Lenny, All This Panic). La cinta cuenta en su reparto con Josephine Langford (Siete deseos) como Tessa y Hero Fiennes Tiffin (Safe) como Hardin, ademas de Selma Blair (Mama y papa), Jennifer Beals (El ultimo magnate), Peter Gallagher (El gran desmadre (Malas madres 2)) y Meadow Williams (Juego de ladrones: El atraco perfecto).', 'after.jpg'),
(24, 'A Silent Voice', '16 de marzo de 2018', 'Animacion', 'Miyu Irino, Saori Hayami', '¿Hasta donde estarias dispuesto a llegar para redimirte? Esta historia trata sobre las consecuencias que traen el querer destacar sobre el resto a toda costa. Algo que le ha pasado a Shōya Ishida, un chico que se burla de su companera, Shōko Nishimiya, por ser sorda. Ella al sentir el acoso por parte de su companero tiene que cambiarse de colegio. Pasado los anos Ishida se arrepiente de su mal comportamiento y querra reencontrarse con su companera para hacer todo lo posible para obtener su perdon. Naoko Yamada (K-On, Eiga Keion) dirige la adaptacion de la novela manga de Yoshitoki Ōima. Miyu Irino (El jardin de las palabras, El viaje de Chihiro) y Saori Hayami (Boruto: Naruto the movie) doblan las voces de los dos protagonistas de esta pelicula de animacion.', 'silen.jpg'),
(25, 'Coco', '1 de diciembre de 2017', 'Animacion', ' Anthony Gonzalez', 'En un pequeno y alegre pueblo mexicano vive Miguel, un nino de 12 anos que pertenece a una familia de zapateros, en la que la musica esta prohibida. Durante generaciones, los Rivera han censurado la musica porque creen que hay una maldicion en ella. Y es que, hace muchos anos, su bisabuelo abandono a su mujer para seguir su sueno de ser musico, y por eso la musica se declaro muerta para todos ellos. \r\n\r\nClaro que Miguel guarda en su interior el anhelo de ser musico. A pesar de la maldicion familiar, Miguel no desiste ya que ama la musica y no va a renunciar a sus suenos tan facilmente. Su sueno es tocar la guitarra, inspirado por su cantante favorito de todos los tiempos, Ernesto de la Cruz. En la manana del Dia de Muertos, el joven se vera envuelto en una fantastica aventura junto a su perro Dante. Ambos lograran entrar al Mundo de los Muertos, donde conoceran a sus antepasados, ademas de a un espiritu amigo llamado Hector. Con la festividad del Dia de Muertos como telon de fondo, Coco nos trasladara a este mundo colorido y musical que es una celebracion de la vida, de la familia, los recuerdos y la conexion a traves de diversas generaciones.', 'coco.jpg'),
(26, 'Sen to Chihiro', '18 de octubre de 2002', 'Animacion', 'Rumi Hiiragi, Miyu Irino', 'Chihiro es una nina de diez anos que esta mudandose con sus padres a un nuevo hogar. Por el camino, la familia se topa con un enorme edificio rojo en cuyo centro se abre un largo tunel. Al otro lado del pasadizo se dibuja una ciudad fantasma. En el restaurante abandonado de esta ciudad, los padres de Chihiro encuentran una gran variedad de platos deliciosos y deciden quedarse a comer, pero, al probar bocado, se transforman en cerdos. Presa del panico, Chihiro huye y empieza a desmaterializarse poco a poco. El enigmatico Haku le explicara el funcionamiento del universo en el que ha caido. Para salvar a sus padres, la nina tendra que enfrentarse a la terrible Yubaba, que tiene el aspecto de una arpia diabolica.', 'chihiro.jpg'),
(27, 'Up', '30 de julio de 2009', 'Animacion', 'Edward Asner, Jordan Nagai', 'Cuando amenazan con demoler su vivienda para construir un establecimiento, Carl Fredricksen, un antiguo vendedor de globos de 78 anos, decide que ha llegado el momento de hacer realidad el sueno que siempre habia compartido con su ya difunta esposa Ellie: explorar Sudamerica a lo largo y a lo ancho del continente. Sin pensarselo mucho, el anciano ata su casa a miles de globos y emprende un viaje a traves del aire.\r\n\r\nSin embargo, la alegria del Sr. Fredicksen comienza a esfumarse cuando descubre que no esta solo, sino que Russell, un pequeno boy scout vendedor de galletas, viaja con el. A diferencia del anciano, el nino esta encantado con haberse incorporado al viaje en el ultimo momento y ambos viviran un viaje repleto de aventuras alucinantes, paisajes incomparables y, por desgracia, tambien de peligros.', 'up.jpg'),
(28, 'inside out', '17 de julio de 2015', 'Animacion', 'Amy Poehler, Bill Hader', 'El paso del tiempo puede ser un camino complicado. Tambien lo es para la joven Riley Anderson cuando, con solo 11 anos, tiene que dejar atras su vida en el Medio Oeste y mudarse a San Francisco. \r\n\r\nComo el resto de las personas, la vida de Riley se guia por sus emociones: Alegria, Miedo, Ira, Asco y Tristeza. Todas ellas viven en el Cuartel General, el centro de control dentro de su cabeza desde donde ayudan y dirigen los comportamientos de la chica en su dia a dia. \r\n\r\nAunque Alegria intenta dominar los sentimientos para mantener a la nina en un estado de felicidad, Tristeza comienza a cambiar las cosas y a hacer que la melancolia se extienda. Una serie de sucesos hace que las dos emociones salgan accidentalmente del Cuartel General y viajen por la mente de Riley mientras tratan de encontrar el camino de vuelta', 'inten.jpg'),
(29, 'Intocable', '9 de marzo de 2012', 'Comedia', ' François Cluzet, Omar Sy, Anne Le Ny', 'Philippe (François Cluzet, \'No se lo digas a nadie\') es un hombre adinerado que pertenece a la alta sociedad. Sin embargo, su vida cambiara para siempre despues de un aparatoso accidente de parapente que lo dejara invalido y en silla de ruedas. Ya no podra hacer nada por si mismo, asi que tendra que contratar a un asistente para que le ayude a desplazarse y a cuidar de el en la casa. La persona que quedara a su cargo sera Driss (Omar Sy, \'Micmacs\'), un joven de color necesitado de dinero que procede de un barrio marginal y que para colmo acaba de ser liberado de la carcel. Aunque parecen destinados a no llevarse bien, Philippe y Driss encontraran el uno en el otro la ilusion que les falta en sus vidas. Aprenderan a apreciar y a mezclar a Vivaldi con el hip hop, los trajes hechos a medida con la ropa holgada y el chandal y la exquisitez en el paladar con la hamburguesa callejera. Si separados son personas fragiles, juntos seran intocables. \r\n\r\nEl tandem de directores formado por Eric Toledano y Olivier Nakache ha conseguido un exito rotundo de taquilla en Francia, convirtiendose \'Intocable\' en la pelicula mas vista de la temporada en el pais vecino.', 'intocable.jpg'),
(30, 'Deadpool', '19 de febrero de 2016 ', 'Comedia, Accion', 'Ryan Reynolds, Morena Baccarin', 'Despues de alistarse en el ejercito, Wade Wilson (Ryan Reynolds) comienza a realizar trabajos de mercenario, y acabara siendo agente de las Fuerzas Especiales de EE.UU. Ya retirado, en su vida civil se dedica a ser un \"maton a sueldo\", ayudando a gente que no puede defenderse por si sola. Su vida transcurre de forma normal, junto a su novia Vanessa (Morena Baccarin), hasta que llega la terrible noticia de que esta gravemente enfermo.\r\n\r\nSus dias estan contados y por eso, para salvar su vida, decide ganar tiempo sometiendose al \"Arma X\": un arriesgado experimento que provoca una alteracion genetica en su organismo, deteniendo asi la enfermedad y haciendole renacer como un indestructible antiheroe cuyo nombre es Deadpool. Eso si, despues de someterse a este complicado experimento, el rostro y el cuerpo de Wilson quedan terriblemente desfigurados. De modo que, decide tomarse con algo mas de humor su drama personal, y es entonces cuando Deadpool se lanza a hacer comentarios jocosos, sea cual sea la situacion a la que se enfrenta.', 'dea.jpg');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `series`
--

CREATE TABLE `series` (
  `idserie` int(11) NOT NULL,
  `titulo` varchar(100) CHARACTER SET utf8 NOT NULL,
  `year` varchar(100) CHARACTER SET utf8 NOT NULL,
  `generos` varchar(100) CHARACTER SET utf8 NOT NULL,
  `actores` text COLLATE utf8_spanish2_ci NOT NULL,
  `descripcion` text CHARACTER SET utf8 NOT NULL,
  `imagen` text COLLATE utf8_spanish2_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

--
-- Volcado de datos para la tabla `series`
--

INSERT INTO `series` (`idserie`, `titulo`, `year`, `generos`, `actores`, `descripcion`, `imagen`) VALUES
(1, 'Breaking Bad', '2008-2013', 'suspenso', 'Walter White', 'En el mundo de las series en television no hay ninguna mejor que Breaking Bad, la historia del timido profesor de quimica Walter White que termina convirtiendose en un temible capo de la droga. Asi lo consideran los usuarios de las plataformas FilmAffinity e IMDb, segun los datos recogidos por Escaparate para elaborar la lista de las mejores series y miniseries de ficcion —al ser documental, no se incluye la miniserie Planeta Tierra— a partir del cruce de las 50 mas votadas en ambas plataformas de critica y recomendacion. En esta clasificacion, compuesta por 15 producciones que coinciden en ambas paginas y que se puede consultar debajo, aparecen por detras otras grandes referencias como The Wire, Juego de tronos, Hermanos de sangre y Los Soprano.', 'Breaking.jpg'),
(2, 'The Wire', '2002-2008', 'policial', 'David Simon', 'Estamos acostumbrados a aceptar la elipsis en casi todas las series policiales. Incluso en 24, donde por regla no debiera haber baches en el tiempo.\r\n\r\nLa elipsis es la forma habitual de hacer mas veloz una historia. El caso mas exagerado de sintesis argumental se da en CSI, donde todo ocurre de un modo perfecto: los testigos hablan rapido, los acusados se desmoronan enseguida, los forenses llegan a tiempo a la escena, los jueces dictaminan pronto, los resultados de balistica ocurren en un tris, etcetera. Esto no habla mal de un guion policial: al contrario. Es un pacto de suspension de realidad entre el espectador y la narracion. El objetivo es tener una trama cerrada en 45 minutos.', 'wire.jpg'),
(3, 'Juego de tronos', '2011-Actualidad', 'accion & AVENTURA', 'David Benioff y D. B. Weiss', 'Juego de tronos es noticia cuando comienza una nueva temporada, pero tambien cuando se filtra un capitulo, cuando HBO es hackeada o cuando uno de los personajes logra que un dragon cabreado ronronee como un gatito. La serie, basada en las novelas de George R. R. Martin, ha abandonado hace anos el terreno de la television para convertirse en algo mucho mas real, como ocurrio con La guerra de las galaxias o El senor de los anillos. El problema esta en saber si nos estamos pasando con nuestra pasion por lo que ocurre en los Siete Reinos, si ha dejado de ser una ficcion para convertirse en una obsesion.', 'got.jpg'),
(4, 'Hermanos de sangre', '2001', 'CRIME DRAMAS', 'Stephen Ambrose', 'Tom Hanks y Steven Spielberg trasladaron a la television el espiritu que les habia llevado a crear Salvar al soldado Ryan tres anos antes: filmar la Segunda Guerra Mundial con unos enormes medios tecnicos y con efectos especiales salvajemente realistas. El mensaje desde el punto de vista de la produccion era que se podia hacer television con los mismos medios que el cine y se gastaron 150 millones de euros en diez episodios para demostrarlo. Hermanos de sangre abrio el camino a series como Juego de tronos. El mensaje desde el punto de vista etico fue que incluso las guerras justas son salvajes, que la lucha contra las nazis fue imprescindible, pero que eso no le quita crueldad y sufrimiento aquellos que viven el conflicto. La serie esta dedicada por eso a “todas las generaciones que han tenido la suerte de no vivir una guerra”.', 'hermanos.jpg'),
(5, 'Los Soprano', '1999-2007', 'COMEDIAS DRAMATICAS', 'David Chase', 'En el fondo, todas estas maravillosas series empezaron con las palabras de los escritores que las crearon y fueron sostenidas por los escritores que se unieron al staff o colaboraron con episodios individuales\", comunico el WGA, citado por The Hollywood Reporter. \"Esta lista no es solo un tributo a la gran television, es una dedicatoria a todos los escritores que entregan sus corazones y sus mentes a promover sus oficios', 'soprano.jpg'),
(6, 'Rick y Morty', '2013-Actualidad', 'CIENCIA FICCION', 'Dan Harmon y Justin Roiland', 'Rick es el protagonista de la serie animada Rick and Morty, cuyo punto de partida podria ser el de una serie infantil clasica: un abuelo cientifico se lleva de aventuras por el universo a su nieto de 14 anos. Pero en realidad Rick es un alcoholico que abandono a su mujer y a su hija, y que usa al pobre Morty como escudo.', 'rick.jpg'),
(7, 'True Detective', '2014-Actualidad', 'CRIME DRAMAS', 'Nic Pizzolatto', 'asi siempre llovia en aquella ciudad sin nombre, tan parecida a las nuestras. Un viejo policia negro, cerebral, solitario, metodico, asqueado, que distrae su insomnio y su angustia en sus interminables noches lanzando la navaja sobre una diana inmovil, escuchando el tictac de un metronomo y leyendo una vez mas a los clasicos, que cuenta las horas para su anhelada jubilacion y alejarse de un mundo siniestro en el que cada vez le cuesta mas respirar, recibe una ultima mision. Debe asociarse con un policia joven, impulsivo, visceral, suspicaz ante la complejidad mental y el estudio de la naturaleza humana como metodo para investigar crimenes que a el le resultan elementales, para encontrar al sofisticado monstruo que asesina con refinada crueldad a personas que representan los pecados capitales. Esta impresionante pelicula se titula Seven y aguanta con su arte y su espanto intactos multiples revisiones.', 'true.png'),
(8, 'El decalogo', '1989', 'CIENCIA FICCION', 'Krzysztof Kieslowski', 'Escuchen con atencion estas tramas: un empleado de correos espia con un telescopio a una mujer desde la ventana de su edificio; una violinista espera un hijo de su amante mientras su marido agoniza; una hija descubre un sobre de su padre vivo con la inscripcion \"para abrir despues de mi muerte\"; una profesora de etica se reencuentra con una mujer judia a la que le nego su ayuda durante la Segunda Guerra Mundial. Y asi hasta diez.', 'decalogo.jpg'),
(9, 'Los Simpson', '1989-Actualidad', 'COMEDIAS DRAMATICAS', 'Matt Groening, Sam Simon y James L. Brooks', 'Su vinculacion fue inmediata, bautizando a los personajes con los nombres de su propia familia: Homer, su padre; su madre, Marge; su hermana, Lisa; y hasta su hermana Maggie, la menor a la que le gustaba tanto el chupete como al personaje animado. Para Bart, su creador uso un sonido parecido a su propio nombre ademas de ligeramente descriptivo (similar a brat, vocablo ingles para definir a alguien mas que travieso). Con este plantel, Groening respondio a la oferta del productor televisivo James L. Brooks de reinventar la animacion en television sin poner en peligro su serie de tiras comicas Life in Hell. “Nadie se habia atrevido a tratar una serie animada que fuera dirigida a alguien mas que a los ninos”, analizo Bill Plympton, director de animacion y uno de los ultimos colaboradores de esta serie en la famosa escena del sillon con la que comienzan todos los ', 'simpson.jpg'),
(10, ' Fargo', '2014-Actualidad', ' DRAMAS HISTORICOS', 'Noah Hawley', 'En sus memorias, el escritor peruano Alfredo Bryce Echenique recuerda un viejo dicho mexicano que viene muy bien para definir la serie Fargo, que se estreno el domingo por la noche en Canal + Series (y que puede verse completa en Yomvi desde ese dia): \"Es como la cerveza de barril y la cerveza de botella: es lo mismo, nomas que diferente\". En principio, la obra maestra de los hermanos Coen parecia imposible de imitar, es una pelicula tan desmesuradamente buena que casi se ha convertido en un adjetivo: cuando algo se parece a Fargo sabemos perfectamente que quiere decir.', 'fargo.jpg'),
(11, 'Fullmetal Alchemist: Brotherhood', '2009-2010', 'CIENCIA FICCION', 'Hiromu Arakawa', 'En este anime de aventuras sobrenaturales, los hermanos Edward y Alphonse subestiman el tremendo poder de una ciencia oculta con el que pretenden revivir a su madre', 'full.jpg'),
(12, 'Monty Python s Flying Circus', '1969-1974', ' COMEDIAS DRAMATICAS', 'Graham Chapman, John Cleese, Terry Gilliam, Eric Idle, Terry Jones y Michael Palin', 'Si hoy el humor de la television inglesa es bueno (recordemos Little Britain e IT Crowd, por poner dos ejemplos actuales) se debe en un porcentaje muy alto a los Monty Python\'s, que practicaron una revolucion universal en el humor del siglo XX, una lobotomia de cerebro a lo establecido y un piquete de ojos a la gente que nunca se rie de nada.', 'come.jpg'),
(13, 'Black Mirror', '2011-Actualidad', 'CIENCIA FICCION', 'Charlie Brooker', 'No hay otra serie como Black Mirror en television. Eso lo sabemos desde que esta antologia de ciencia ficcion sobre tecnologia y comunicacion en el siglo XXI aterrizo en 2011 en el canal britanico Channel 4. La creacion de Charlie Brooker, provocadora y directa, no tardo en ser un fenomeno. En 2016 llevo a cabo su salto internacional gracias a la plataforma digital Netflix, que produjo seis nuevos capitulos, los que componian su tercera temporada. La cuarta llego cuando 2017 estaba a punto de despedirse, con otros seis episodios independientes y muy distintos entre si (que ya has podido puntuar). De esta forma, la serie ya suma 19 episodios, que a continuacion ordenamos de peor a mejor (siempre teniendo en cuenta que hasta los peores son mejores que la mayoria de la ficcion televisiva actual). Por supuesto, aunque quizas no haga falta recordarlo, la lista es subjetiva y abierta a toda discusion (A finales de 2018, Netflix estreno la pelicula Bandersnatch).', 'black.jpg'),
(14, 'Friends', '1994-2004', 'COMEDIAS IRREVENTES', 'David Crane y Marta Kauffman', 'Que tiene Friends para ser una serie que ha marcado a varias generaciones de espectadores? Con marcado me refiero a que ha entrado a formar parte de nuestros recuerdos casi con la misma intensidad que la realidad, que ha logrado instalarse en nuestras existencias. La serie, que relata la historia de seis amigos en Manhattan, a lo largo de una decada, se apoya en unos guiones impresionantes, unos personajes que funcionan muy bien porque se mueven dentro de unas caracteristicas muy marcadas sin agotarlas nunca, un ingenio imbatible en los gags y unos actores estupendos, desde los seis protagonistas hasta el ultimo secundario. Pero hay algo que convierte a Friends en una ficcion invencible: que nos habla de nosotros mismos, es una serie sobre la vida, con la que hemos madurado a la vez que sus personajes.', 'friends.jpg'),
(15, 'Sherlock', '2010-Actualidad', 'DRAMAS HISTORICOS', 'Steven Moffat y Mark Gatiss', 'Una de las mejores cosas del Sherlock de la BBC creado por Steven Moffat y Mark Gatiss es el perfecto encaje de los dos personajes con los tiempos modernos. Trasladar con exito a Holmes y Watson al siglo XXI sin traicionar su esencia no era una tarea sencilla. Pero gracias a la pericia de sus guionistas, a ese especial cuidado que ponen las producciones de la BBC en su acabado visual y a la gran labor de unos actores en estado de gracia, en Sherlock todas las piezas encajan. El unico problema es que hay que esperar demasiado entre temporada y temporada (los compromisos laborales de todos sus implicados, desde creadores hasta actores, no pone las cosas demasiado faciles) y que cada entrega tiene solo tres capitulos.', 'Sherlock.jpg'),
(16, 'The Good Doctor', 'Desde 2017', 'Drama, Medico', 'Freddie Highmore, Nicholas Gonzalez', 'The Good Doctor se centra en un joven y brillante cirujano que padece el sindrome de Savant. Poco se sabe de este \"sindrome del sabio\" ademas de que aquellos que lo sufren tienen una memoria', 'doctor.jpg'),
(17, 'Los 100', 'Desde 2014', 'Aventura, Drama, Ciencia ficcion', 'Eliza Taylor, Paige Turco, Bob Morley', 'es un drama post apocaliptico escrito por Jason Rothenberg (Body Politic), basado en los libros de Kass Morgan. La historia esta centrada en lo que ocurre con la civilizacion casi cien ', 'cien.jpg'),
(18, 'Erkenci Kus', 'Desde 2018', 'Comedia, Romantico', ' Ayse Kutlu', 'Erkenci Kus (pajaro sonador) es una telenovela turca que se centra en la historia de amor entre una joven sonadora, Sanem, y el hijo del dueno de una prestigiosa agencia de publicidad, Can. Esta', 'pajaro.jpg'),
(19, 'Anatomia de Grey', 'Desde 2005', 'Drama, Medico', 'Betsy Beers, Shonda Rhimes', 'Meredith Grey (Ellen Pompeo, \'Daredevil\', \'El compromiso\') es hija de una de las cirujanas mas respetadas de la profesion. Ahora, ella quiere seguir los pasos de su madre en el Hospital Grace de', 'grey.jpg'),
(20, 'Lucifer', 'Desde 2016', 'Drama, Fantasia, Crimen', 'Joe Henderson, Tom Kapinos', 'La historia de Lucifer es la que todos conocemos: un angel caido del cielo. Sin embargo, este senor del infierno esta aburrido de su propia existencia. Por ello, Lucifer decide abandonar su reino', 'lucifer.jpg'),
(21, 'Skam Espana', 'Desde 2018', 'Drama', 'Begona Alvarez Rojas', 'Skam Espana es un retrato de los jovenes de 16 anos nacidos a partir del 2000. Los temas en los que se centra esta serie son: el acoso sexual, el femenismo, el bullying, la homofobia, la', 'skam.jpg'),
(22, 'The Walking Dead', 'Desde 2010', 'Drama, Terror', ' Glen Mazzara, Frank Darabont, Scott M. Gimple', 'La historia nos traslada a un escenario post-pandemico en el que un virus ha acabado con la practica totalidad de la poblacion mundial convirtiendolos en zombis. Seremos testigo de la lucha de un ', 'walking.jpg'),
(23, 'Vikingos', 'Desde 2013', 'Aventura, Drama, Historico', 'Michael Hirst', 'Este nuevo drama historico, dirigido por Michael Hirst (\'Elizabeth\', \'The Tudors\'), de History Channel esta centrado en Ragnar Lothbrok, figura mitica que aseguraba que era el descendiente de ', 'Vikings.jpg'),
(24, 'Riverdale', 'Desde 2017', 'Drama, Suspense', 'Roberto Aguirre-Sacasa', 'Al mismo tiempo que un nuevo ano escolar da comienzo, la ciudad de Riverdale aun esta reponiendose de la tragica muerte reciente de Jason Blossom. Los acontecimientos que han tenido lugar durante', 'Riverdale.jpg'),
(25, 'Stiletto Vendetta', '2017 - 2018', ' Drama', 'Meriç Acemi', 'Stiletto Vendetta es una serie de Turquia que gira en torno al reencuentro de cuatro amigas de la infancia con grandes exitos. Estas cuatro mujeres son apasionadas, inteligentes, agradables y con ', 'stilentto.jpg'),
(26, 'Cobra Kai', 'Desde 2018', 'Drama, Artes Marciales', 'Josh Heald, Jon Hurwitz', 'Cobra Kai es la secuela de la famosa saga cinematografica Karate Kid. La serie sigue la historia 30 anos despues del campeonato de 1984, Johnny no se encuentra en el mejor momento de su vida por lo', 'kai.jpg'),
(27, 'Instinto', 'Desde 2018', 'Erotico, Suspense', 'Teresa Fernandez-Valdes', 'Marco es un joven, atractivo y deseado empresario lider de ALVA, una de las companias tecnologicas mas exitosas a nivel internacional.  Ademas, se encuentra en un momento importante de su', 'instinto.jpg');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `peliculas`
--
ALTER TABLE `peliculas`
  ADD PRIMARY KEY (`idpelicula`);

--
-- Indices de la tabla `series`
--
ALTER TABLE `series`
  ADD PRIMARY KEY (`idserie`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `peliculas`
--
ALTER TABLE `peliculas`
  MODIFY `idpelicula` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- AUTO_INCREMENT de la tabla `series`
--
ALTER TABLE `series`
  MODIFY `idserie` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=28;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
